ALTER TYPE "TaskBoardAutomationRuleType" ADD VALUE 'STALE_TASK_FOLLOW_UP';
ALTER TYPE "TaskBoardAutomationRuleType" ADD VALUE 'CHECKLIST_INCOMPLETE_BEFORE_DUE';
ALTER TYPE "TaskBoardAutomationRuleType" ADD VALUE 'OVERDUE_ESCALATION';

ALTER TYPE "NotificationTemplateKey" ADD VALUE 'TASK_BOARD_AUTOMATION_STALE_TASK_FOLLOW_UP';
ALTER TYPE "NotificationTemplateKey" ADD VALUE 'TASK_BOARD_AUTOMATION_CHECKLIST_INCOMPLETE_BEFORE_DUE';
ALTER TYPE "NotificationTemplateKey" ADD VALUE 'TASK_BOARD_AUTOMATION_OVERDUE_ESCALATION';
