'use client';

import { useEffect, useMemo, useState } from 'react';
import { Area, AreaChart, CartesianGrid, Legend, Line, LineChart, PolarAngleAxis, PolarGrid, Radar, RadarChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import { AppSelect } from './app-select';
import { Card } from './ui';

export type DeliveryStatusKey = 'failed' | 'sent';
export type DeliveryStatusTotal = { key: DeliveryStatusKey; label: string; value: number; color: string };
export type DeliveryTrendPoint = { label: string; sent: number; failed: number; date: string };
export type CampaignStatusPoint = { status: string; count: number };
export type EmailTrendRange = '7d' | '30d' | '90d';

export function DeliveryStatusDistributionLineCard({ emptyText, lang, title, totals, trendData, timeZone }: { emptyText: string; lang: string; title: string; totals: DeliveryStatusTotal[]; trendData: DeliveryTrendPoint[]; timeZone?: string }) {
  const locale = lang === 'fr' ? 'fr-FR' : 'en-US';
  const [activeStatus, setActiveStatus] = useState<DeliveryStatusKey>('failed');
  const active = totals.find((item) => item.key === activeStatus) ?? totals[0] ?? null;
  const hasTrendData = trendData.some((item) => item.failed > 0 || item.sent > 0);
  useEffect(() => {
    const preferredStatus = totals.find((item) => item.value > 0)?.key ?? (hasTrendData ? (trendData.some((item) => item.failed > 0) ? 'failed' : 'sent') : totals[0]?.key);
    if (preferredStatus && !totals.some((item) => item.key === activeStatus && (item.value > 0 || hasTrendData))) setActiveStatus(preferredStatus);
  }, [activeStatus, hasTrendData, totals, trendData]);
  return <Card className="overflow-hidden rounded-2xl border-white/10 bg-[linear-gradient(180deg,rgba(255,255,255,0.055),rgba(255,255,255,0.025))] p-0"><div className="flex flex-col items-stretch border-b border-white/10 xl:flex-row"><div className="flex flex-1 flex-col justify-center gap-1 px-5 py-4"><h2 className="text-sm font-semibold text-white/82">{title}</h2><p className="text-xs leading-5 text-white/45">{lang === 'fr' ? 'Résultats d’envoi par statut.' : 'Delivery outcomes by status.'}</p></div>{totals.length > 0 && <div className="grid grid-cols-2 border-t border-white/10 xl:flex xl:border-l xl:border-t-0">{totals.map((item) => { const selected = active?.key === item.key; return <button key={item.key} type="button" onClick={() => setActiveStatus(item.key)} className={`flex min-w-[7.25rem] flex-col justify-center gap-1 border-l border-white/10 px-4 py-3 text-left transition first:border-l-0 hover:bg-white/[0.045] focus:outline-none focus:ring-2 focus:ring-emerald-300/35 ${selected ? 'bg-white/[0.065]' : ''}`} aria-pressed={selected}><span className="inline-flex items-center gap-2 text-xs text-white/55"><span className="h-2 w-2 rounded-full" style={{ backgroundColor: item.color }} />{item.label}</span><span className="text-xl font-semibold leading-none text-white">{item.value.toLocaleString(locale)}</span></button>; })}</div>}</div><div className="px-2 py-5 sm:p-6">{!hasTrendData || !active ? <div className="flex h-[250px] items-center justify-center rounded-xl border border-dashed border-white/10 bg-black/10 px-4 text-center text-sm text-white/50">{emptyText}</div> : <div className="h-[250px]"><ResponsiveContainer width="100%" height="100%"><LineChart data={trendData} margin={{ top: 16, right: 18, left: -12, bottom: 0 }}><CartesianGrid stroke="rgba(255,255,255,0.08)" vertical={false} /><XAxis dataKey="date" tickLine={false} axisLine={false} tickMargin={8} minTickGap={28} tick={{ fill: 'rgba(255,255,255,0.55)', fontSize: 11 }} tickFormatter={(value) => formatTrendTick(String(value), locale, timeZone)} /><YAxis tick={{ fill: 'rgba(255,255,255,0.42)', fontSize: 11 }} axisLine={false} tickLine={false} allowDecimals={false} /><Tooltip content={<DeliveryStatusTooltip activeStatus={active} locale={locale} timeZone={timeZone} />} cursor={{ stroke: 'rgba(255,255,255,0.12)', strokeWidth: 1 }} /><Line type="monotone" dataKey={active.key} name={active.label} stroke={active.color} strokeWidth={2.5} dot={false} activeDot={{ r: 5, fill: active.color, strokeWidth: 0 }} /></LineChart></ResponsiveContainer></div>}</div></Card>;
}

export function CampaignsByStatusRadarCard({ data, emptyText, lang, title }: { data: CampaignStatusPoint[]; emptyText: string; lang: string; title: string }) {
  const hasData = data.some((item) => item.count > 0);
  return <Card className="rounded-2xl border-white/10 bg-[linear-gradient(180deg,rgba(255,255,255,0.055),rgba(255,255,255,0.025))] p-5"><div className="mb-4 space-y-1"><h2 className="text-sm font-semibold text-white/82">{title}</h2><p className="text-xs leading-5 text-white/45">{lang === 'fr' ? 'Totaux des campagnes regroupés par statut actuel.' : 'Campaign totals grouped by current status.'}</p></div>{!hasData ? <div className="flex h-[250px] items-center justify-center rounded-xl border border-dashed border-white/10 bg-black/10 px-4 text-center text-sm text-white/50">{emptyText}</div> : <div className="mx-auto h-[270px] max-w-[340px]"><ResponsiveContainer width="100%" height="100%"><RadarChart data={data} margin={{ top: 24, right: 28, bottom: 24, left: 28 }}><Tooltip content={<CampaignStatusTooltip />} cursor={false} /><PolarAngleAxis dataKey="status" tick={(props) => <CampaignStatusTick {...props} data={data} />} /><PolarGrid stroke="rgba(255,255,255,0.13)" radialLines /><Radar dataKey="count" name={lang === 'fr' ? 'Campagnes' : 'Campaigns'} fill="#5ed29c" stroke="#5ed29c" fillOpacity={0.38} strokeWidth={2.25} /></RadarChart></ResponsiveContainer></div>}</Card>;
}

export function RecentDeliveryTrendAreaChart({ data, emptyText, lang, onTimeRangeChange, timeRange, title, timeZone }: { data: DeliveryTrendPoint[]; emptyText: string; lang: string; onTimeRangeChange: (value: EmailTrendRange) => void; timeRange: EmailTrendRange; title: string; timeZone?: string }) {
  const locale = lang === 'fr' ? 'fr-FR' : 'en-US';
  const filteredData = useMemo(() => filterTrendData(data, timeRange), [data, timeRange]);
  const hasSent = filteredData.some((item) => item.sent > 0);
  const hasFailed = filteredData.some((item) => item.failed > 0);
  const hasData = hasSent || hasFailed;
  return <Card className="rounded-2xl border-white/10 bg-[linear-gradient(180deg,rgba(255,255,255,0.052),rgba(255,255,255,0.026))] p-5"><div className="mb-4 flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between"><div><h2 className="text-sm font-semibold text-white/82">{title}</h2><p className="mt-1 text-xs leading-5 text-white/45">{lang === 'fr' ? (hasFailed ? 'Destinataires envoyés et échoués au fil du temps.' : 'Destinataires envoyés au fil du temps.') : (hasFailed ? 'Sent and failed recipients over time.' : 'Sent recipients over time.')}</p></div><AppSelect value={timeRange} options={trendRangeOptions(lang)} onChange={onTimeRangeChange} className="min-w-[9.5rem] sm:w-[10rem]" /></div>{!hasData ? <div className="flex h-[250px] items-center justify-center rounded-xl border border-dashed border-white/10 bg-black/10 px-4 text-center text-sm text-white/50">{emptyText}</div> : <div className="h-[250px]"><ResponsiveContainer width="100%" height="100%"><AreaChart data={filteredData} margin={{ top: 10, right: 12, left: -18, bottom: 0 }}><defs><linearGradient id="emailTrendSentFill" x1="0" y1="0" x2="0" y2="1"><stop offset="5%" stopColor="#5ed29c" stopOpacity={0.7} /><stop offset="95%" stopColor="#5ed29c" stopOpacity={0.08} /></linearGradient><linearGradient id="emailTrendFailedFill" x1="0" y1="0" x2="0" y2="1"><stop offset="5%" stopColor="#fb7185" stopOpacity={0.58} /><stop offset="95%" stopColor="#fb7185" stopOpacity={0.06} /></linearGradient></defs><CartesianGrid stroke="rgba(255,255,255,0.08)" vertical={false} /><XAxis dataKey="date" tickLine={false} axisLine={false} tickMargin={8} minTickGap={28} tick={{ fill: 'rgba(255,255,255,0.55)', fontSize: 11 }} tickFormatter={(value) => formatTrendTick(String(value), locale, timeZone)} /><YAxis tick={{ fill: 'rgba(255,255,255,0.42)', fontSize: 11 }} axisLine={false} tickLine={false} allowDecimals={false} /><Tooltip content={<DeliveryTrendTooltip locale={locale} timeZone={timeZone} />} cursor={{ stroke: 'rgba(255,255,255,0.12)', strokeWidth: 1 }} /><Legend content={<DeliveryTrendLegend />} />{hasSent && <Area type="monotone" dataKey="sent" name={lang === 'fr' ? 'Envoyés' : 'Sent'} stroke="#5ed29c" strokeWidth={2.5} fill="url(#emailTrendSentFill)" fillOpacity={1} dot={false} activeDot={{ r: 5, fill: '#5ed29c', strokeWidth: 0 }} />}{hasFailed && <Area type="monotone" dataKey="failed" name={lang === 'fr' ? 'Échecs' : 'Failed'} stroke="#fb7185" strokeWidth={2.1} fill="url(#emailTrendFailedFill)" fillOpacity={1} dot={false} activeDot={{ r: 4, fill: '#fb7185', strokeWidth: 0 }} />}</AreaChart></ResponsiveContainer></div>}</Card>;
}

function DeliveryStatusTooltip({ active, label, locale, payload, activeStatus, timeZone }: { active?: boolean; label?: string; locale: string; payload?: Array<{ value?: number }>; activeStatus: DeliveryStatusTotal | null; timeZone?: string }) { if (!active || !payload?.length || !activeStatus) return null; const value = payload[0]?.value; if (typeof value !== 'number') return null; return <div className="rounded-xl border border-white/10 bg-[#101815]/95 px-3 py-2 text-xs shadow-2xl shadow-black/45 backdrop-blur"><p className="font-semibold text-white">{formatTrendTooltipLabel(label ?? '', locale, timeZone)}</p><p className="mt-1" style={{ color: activeStatus.color }}>{activeStatus.label}: {value.toLocaleString(locale)}</p></div>; }
function CampaignStatusTooltip({ active, payload, label }: { active?: boolean; payload?: Array<{ value?: number; payload?: CampaignStatusPoint }>; label?: string }) { if (!active || !payload?.length) return null; const item = payload[0]; const value = item.payload?.count ?? item.value; if (typeof value !== 'number') return null; return <div className="rounded-xl border border-white/10 bg-[#101815]/95 px-3 py-2 text-xs shadow-2xl shadow-black/45 backdrop-blur"><p className="font-semibold text-white">{item.payload?.status ?? label}</p><p className="mt-1 text-accent">{value.toLocaleString()}</p></div>; }
function CampaignStatusTick({ x, y, textAnchor, index, data }: { x?: number; y?: number; textAnchor?: 'start' | 'middle' | 'end' | 'inherit'; index?: number; data: CampaignStatusPoint[] }) { const item = typeof index === 'number' ? data[index] : null; if (!item || typeof x !== 'number' || typeof y !== 'number') return null; return <text x={x} y={y} textAnchor={textAnchor} className="fill-white/85 text-[11px] font-medium"><tspan x={x}>{item.count.toLocaleString()}</tspan><tspan x={x} dy="1rem" className="fill-white/50 text-[10px]">{item.status}</tspan></text>; }
function DeliveryTrendTooltip({ active, payload, label, locale, timeZone }: { active?: boolean; payload?: Array<{ color?: string; name?: string; value?: number }>; label?: string; locale: string; timeZone?: string }) { if (!active || !payload?.length) return null; const rows = payload.filter((item) => typeof item.value === 'number'); if (!rows.length) return null; return <div className="rounded-xl border border-white/10 bg-[#101815]/95 px-3 py-2 text-xs shadow-2xl shadow-black/45 backdrop-blur"><p className="font-semibold text-white">{formatTrendTooltipLabel(label ?? '', locale, timeZone)}</p><div className="mt-2 space-y-1.5">{rows.map((item) => <div key={item.name} className="flex min-w-28 items-center justify-between gap-4 text-white/68"><span className="inline-flex items-center gap-2"><span className="h-2 w-2 rounded-full" style={{ backgroundColor: item.color ?? '#5ed29c' }} />{item.name}</span><span className="font-semibold text-white">{item.value}</span></div>)}</div></div>; }
function DeliveryTrendLegend({ payload }: { payload?: Array<{ color?: string; value?: string }> }) { if (!payload?.length) return null; return <div className="flex justify-center gap-4 pt-2 text-xs text-white/55">{payload.map((item) => <span key={item.value} className="inline-flex items-center gap-2"><span className="h-2.5 w-2.5 rounded-full" style={{ backgroundColor: item.color ?? '#5ed29c' }} />{item.value}</span>)}</div>; }
function filterTrendData(data: DeliveryTrendPoint[], timeRange: EmailTrendRange) { const dated = data.map((item) => ({ item, date: trendDate(item.date) })).filter((entry): entry is { item: DeliveryTrendPoint; date: Date } => Boolean(entry.date)); if (!dated.length) return data; const referenceDate = new Date(Math.max(...dated.map((entry) => entry.date.getTime()))); const days = timeRange === '7d' ? 7 : timeRange === '30d' ? 30 : 90; const startDate = new Date(referenceDate); startDate.setDate(startDate.getDate() - days); return dated.filter((entry) => entry.date >= startDate).map((entry) => entry.item); }
function trendDate(value: string) { const date = new Date(value); return Number.isNaN(date.getTime()) ? null : date; }
function formatTrendTick(value: string, locale: string, timeZone?: string) { const date = trendDate(value); return date ? new Intl.DateTimeFormat(locale, { month: 'short', day: 'numeric', ...(timeZone ? { timeZone } : {}) }).format(date) : value; }
function formatTrendTooltipLabel(value: string, locale: string, timeZone?: string) { const date = trendDate(value); return date ? new Intl.DateTimeFormat(locale, { dateStyle: 'medium', ...(timeZone ? { timeZone } : {}) }).format(date) : value; }
function trendRangeOptions(lang: string): Array<{ value: EmailTrendRange; label: string }> { return lang === 'fr' ? [{ value: '7d', label: '7 derniers jours' }, { value: '30d', label: '30 derniers jours' }, { value: '90d', label: '90 derniers jours' }] : [{ value: '7d', label: 'Last 7 days' }, { value: '30d', label: 'Last 30 days' }, { value: '90d', label: 'Last 90 days' }]; }
